[package]
name = "marketstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "^0.11.3"
thiserror = "1.0.38"
tokio = "^1.23.0"
tonic = "^0.8.3"

[build-dependencies]
tonic = "^0.8.3"
tonic-build = { version = "0.8.3" }
reqwest = {version = "^0.11.11", features = ["blocking"]}
temp-dir = "^0.1.11"
