name: build and publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - Cargo.toml

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/ananthartha

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: "Unit Test"
      run: cargo test

    - name: "Version Bump"
      run: |
        cargo install cargo-bump
        cargo bump patch

    - uses: SebRollen/toml-action@v1.0.1
      id: version
      with:
        file: 'Cargo.toml'
        field: 'package.version'

    - name: Publish Package
      run: cargo publish --token ${CARGO_REGISTRY_TOKEN}
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: v{{ steps.read_toml.outputs.value }}

    - name: Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
