name: build and publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - Cargo.toml

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/ananthartha

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: "Unit Test"
      run: cargo test

    - name: "Version Bump"
      run: |
        cargo install cargo-bump
        cargo bump patch

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Package bump by action
        file_pattern: Cargo.toml
        skip_checkout: true

    - uses: SebRollen/toml-action@v1.0.1
      id: version
      with:
        file: 'Cargo.toml'
        field: 'package.version'

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: v{{ steps.version.outputs.value }}

    - name: Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Package
      run: cargo publish --token ${CARGO_REGISTRY_TOKEN}
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
